import type { InferredType, Mutation } from "../core/types.js";
import { renderInlineType, renderNamedInterface } from "./types-gen.js";

export interface ClientGenInput {
  baseUrlEnvVar: string;
  mutations: Mutation[];
}

export interface GeneratedClient {
  clientTs: string;
  typesTs: string;
}

export function generateClient(input: ClientGenInput): GeneratedClient {
  const requestTypes: string[] = [];
  const responseTypes: string[] = [];
  const methods: string[] = [];

  for (const mutation of input.mutations) {
    const methodName = methodNameFor(mutation);
    const reqTypeName = `${pascal(methodName)}Input`;
    const resTypeName = `${pascal(methodName)}Result`;

    const inputType = inferInputType(mutation);
    requestTypes.push(renderNamedInterface(reqTypeName, inputType));

    const responseType: InferredType = mutation.responseType ?? { kind: "unknown" };
    responseTypes.push(renderNamedInterface(resTypeName, responseType));

    methods.push(renderMethod(methodName, mutation, reqTypeName, resTypeName));
  }

  const typesTs = [
    `// Auto-generated by reverse-engineering-kit. Do not edit manually.`,
    "",
    ...requestTypes,
    "",
    ...responseTypes,
    "",
  ].join("\n");

  const clientTs = [
    `// Auto-generated by reverse-engineering-kit. Do not edit manually.`,
    `import { classifyApiError } from "./errors.js";`,
    `import type {`,
    ...input.mutations.flatMap((m) => {
      const name = methodNameFor(m);
      return [`  ${pascal(name)}Input,`, `  ${pascal(name)}Result,`];
    }),
    `} from "./types.js";`,
    "",
    `export interface ApiClientOptions {`,
    `  baseUrl: string;`,
    `  fetchImpl?: typeof fetch;`,
    `  defaultHeaders?: Record<string, string>;`,
    `  timeoutMs?: number;`,
    `}`,
    "",
    `export class ApiClient {`,
    `  private readonly baseUrl: string;`,
    `  private readonly fetchImpl: typeof fetch;`,
    `  private readonly defaultHeaders: Record<string, string>;`,
    `  private readonly timeoutMs: number;`,
    "",
    `  constructor(options: ApiClientOptions) {`,
    `    this.baseUrl = options.baseUrl.replace(/\\/+$/, "");`,
    `    this.fetchImpl = options.fetchImpl ?? fetch;`,
    `    this.defaultHeaders = options.defaultHeaders ?? {};`,
    `    this.timeoutMs = options.timeoutMs ?? 15000;`,
    `  }`,
    "",
    `  private async request<T>(opts: {`,
    `    method: string;`,
    `    path: string;`,
    `    query?: Record<string, string | number | boolean | undefined>;`,
    `    body?: unknown;`,
    `    headers?: Record<string, string>;`,
    `  }): Promise<T> {`,
    `    const url = new URL(this.baseUrl + opts.path);`,
    `    if (opts.query) {`,
    `      for (const [k, v] of Object.entries(opts.query)) {`,
    `        if (v !== undefined) url.searchParams.set(k, String(v));`,
    `      }`,
    `    }`,
    `    const controller = new AbortController();`,
    `    const timer = setTimeout(() => controller.abort(), this.timeoutMs);`,
    `    try {`,
    `      const response = await this.fetchImpl(url.toString(), {`,
    `        method: opts.method,`,
    `        headers: {`,
    `          ...(opts.body !== undefined ? { "Content-Type": "application/json" } : {}),`,
    `          ...this.defaultHeaders,`,
    `          ...(opts.headers ?? {}),`,
    `        },`,
    `        body: opts.body !== undefined ? JSON.stringify(opts.body) : undefined,`,
    `        signal: controller.signal,`,
    `      });`,
    `      const text = await response.text();`,
    `      let parsed: unknown = text;`,
    `      try { parsed = text ? JSON.parse(text) : undefined; } catch { /* leave as text */ }`,
    `      if (!response.ok) {`,
    `        throw classifyApiError(response.status, parsed);`,
    `      }`,
    `      return parsed as T;`,
    `    } finally {`,
    `      clearTimeout(timer);`,
    `    }`,
    `  }`,
    "",
    ...methods,
    `}`,
    "",
  ].join("\n");

  return { clientTs, typesTs };
}

function renderMethod(
  methodName: string,
  mutation: Mutation,
  inputTypeName: string,
  resultTypeName: string,
): string {
  const pathParams = pathParamsFromTemplate(mutation.pathTemplate);
  const pathExpr = renderPathExpression(mutation.pathTemplate);
  const isReadOnly = mutation.method === "GET" || mutation.method === "DELETE";
  let bodyExpr: string;
  if (isReadOnly || !mutation.payload) {
    bodyExpr = "undefined";
  } else if (pathParams.length === 0) {
    // inferInputType returns the body schema directly when there are no path params,
    // so the input object IS the body.
    bodyExpr = "input";
  } else {
    bodyExpr = "input.body";
  }
  const params: string[] = [];
  if (pathParams.length > 0 || mutation.payload || pathParams.length === 0) {
    params.push(`input: ${inputTypeName}`);
  }

  return [
    `  async ${methodName}(${params.join(", ")}): Promise<${resultTypeName}> {`,
    `    return this.request<${resultTypeName}>({`,
    `      method: ${JSON.stringify(mutation.method)},`,
    `      path: ${pathExpr},`,
    `      body: ${bodyExpr},`,
    `    });`,
    `  }`,
    "",
  ].join("\n");
}

function renderPathExpression(template: string): string {
  if (!template.includes("{")) return JSON.stringify(template);
  const parts = template.split(/(\{[^}]+\})/);
  const pieces = parts.map((p) => {
    const m = /^\{([^}]+)\}$/.exec(p);
    if (m) return "${" + `encodeURIComponent(input.${camel(m[1]!)})` + "}";
    return p;
  });
  return "`" + pieces.join("") + "`";
}

function pathParamsFromTemplate(template: string): string[] {
  return [...template.matchAll(/\{([^}]+)\}/g)].map((m) => m[1]!);
}

function inferInputType(mutation: Mutation): InferredType {
  const properties: Record<string, InferredType> = {};
  const required: string[] = [];
  for (const param of pathParamsFromTemplate(mutation.pathTemplate)) {
    properties[camel(param)] = { kind: "string" };
    required.push(camel(param));
  }
  if (mutation.payload) {
    const bodyType = payloadToInferredType(mutation.payload.minimal);
    if (Object.keys(properties).length === 0) return bodyType;
    properties.body = bodyType;
    required.push("body");
  } else if (Object.keys(properties).length === 0) {
    return { kind: "object", properties: {}, required: [] };
  }
  return { kind: "object", properties, required };
}

function payloadToInferredType(minimal: Record<string, unknown>): InferredType {
  const properties: Record<string, InferredType> = {};
  const required: string[] = [];
  for (const [k, v] of Object.entries(minimal)) {
    properties[k] = guessTypeForValue(v);
    required.push(k);
  }
  return { kind: "object", properties, required };
}

function guessTypeForValue(v: unknown): InferredType {
  if (typeof v === "string") return { kind: "string" };
  if (typeof v === "number") return { kind: "number", isInteger: Number.isInteger(v) };
  if (typeof v === "boolean") return { kind: "boolean" };
  if (v === null) return { kind: "null" };
  if (Array.isArray(v)) return { kind: "array", items: { kind: "unknown" } };
  if (typeof v === "object") {
    const properties: Record<string, InferredType> = {};
    const required: string[] = [];
    for (const [k, vv] of Object.entries(v as Record<string, unknown>)) {
      properties[k] = guessTypeForValue(vv);
      required.push(k);
    }
    return { kind: "object", properties, required };
  }
  return { kind: "unknown" };
}

function methodNameFor(mutation: Mutation): string {
  return `${mutation.action}${pascal(singularize(mutation.resource))}`;
}

function singularize(word: string): string {
  if (word.endsWith("ies")) return word.slice(0, -3) + "y";
  if (word.endsWith("ses") || word.endsWith("xes") || word.endsWith("zes")) return word.slice(0, -2);
  if (word.endsWith("s") && !word.endsWith("ss")) return word.slice(0, -1);
  return word;
}

function pascal(word: string): string {
  return word
    .split(/[\s_\-{}]+/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}

function camel(word: string): string {
  const p = pascal(word);
  return p.charAt(0).toLowerCase() + p.slice(1);
}

export { camel, pascal };
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const _used: InferredType = { kind: "unknown" }; void _used;
